kind: Service
apiVersion: v1
metadata:
  name: manage-service
spec:
  selector:
    app: manage
  type: NodePort
  ports:
    - protocol: TCP
      port: 30004
      targetPort: 8084
      nodePort: 30004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manage
  labels:
    app: manage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manage
  template:
    metadata:
      labels:
        app: manage
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: maven
        image: 	127.0.0.1:34841/manage-console:${CICD_EXECUTION_SEQUENCE}
        volumeMounts:
          - mountPath: /data/jar
            name: datax
          - mountPath: /etc/timezone
            name: timezone
            readOnly: true
        ports:
        - containerPort: 8084
      volumes:
        - hostPath:
            path: /data/jar/comm
            type: ""
          name: datax
        - hostPath:
            path: /etc/timezone
            type: ""
          name: timezone
